### ISSUE TITLE
Missing package 'fuse'

### ISSUE THREAD

**Issue by jasperblues** [libimobiledevice/ifuse#11]
Build the following deps: 
- libplist
- libusbmuxd
- libimobiledevice

I'm trying to build ifuse now. . . and get: 

checking for libfuse... no
configure: error: Package requirements (fuse >= 2.7.0) were not met:

No package 'fuse' found

. . . can you remind me where 'fuse' comes from?

**Comment by babycaseny** [comment]
I still have this problem after downloading from sourceforge the update.  Anything I can check to know what's wrong?

**Comment by babycaseny** [comment]
I forked a clone of fuse here: https://github.com/babycaseny/fuse-fuse

**Comment by biocyberman** [comment]
The message  `configure: error: Package requirements (fuse >= 2.7.0) were not met:` is misleading. I installed `libfuse-dev` and solved the problem.

**Comment by gitsop01** [comment]
It is a configure error message and is telling you that it cannot find the libfuse-devel package on your system which you worked out.
