### ISSUE TITLE
Better error message for "InstallationLookupFailed" (#24)

### ISSUE THREAD

**Issue by ahti** [libimobiledevice/ifuse#29]
Comments in #24 describe in what cases ifuse will fail with `InstallationLookupFailed`. It would be helpful to provide a better error message in that case, so users don't need to go searching for the error.

Another way to make things more clear might be to list app ids that are actually mountable (related to #28), because most apps will not work anymore.

**Comment by nikias** [comment]
Fixed with https://github.com/libimobiledevice/ifuse/commit/8e633f44d6f744f564ebdbe6cb214d84ca9af69c
