### ISSUE TITLE
Error code -36 when writing files on OS X 10.11.5

### ISSUE THREAD

**Issue by dnicolson** [libimobiledevice/ifuse#30]
Copying files in the Finder to an iOS volume using OSXFUSE 2.8.3 results in an `Error code -36` message. The file is still copied and can be read as well. Duplicating files on the iOS volume does not produce an error.

**Comment by Damian79** [comment]
I am getting an error 36 when copying from OSX 10.11.5 to a WDMYCloud SMB share (Home network drive) using finder. But I am able to copy to an SMB share on Windows without issue. Maybe this version of OSX does not like to copy to ext file system (assuming the WDMyCloud uses that), over SMB.

**Comment by dnicolson** [comment]
Closing this issue as it is no longer reproducible on macOS 10.13.3 and iOS 11.3 when using the `master` branch.
