### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anatoli26** [libimobiledevice/ifuse#34]
Why not to publish a new release and notify the distributions to integrate it to the official repos? The latest 1.1.3 was published 3 years ago and have a lot of issues that the HEAD fixes. Particularly, the 1.1.3 doesn't have --documents option and doesn't mount app folders, but manually compiled (from the HEAD) binary works fine!

**Comment by Peter2121** [comment]
+1 for release, waiting for new port on FreeBSD...

**Comment by FunkyM** [comment]
Closing as version [1.1.4](/libimobiledevice/ifuse/releases/tag/1.1.4) has been released.
