### ISSUE TITLE
Would be great if this was available via MacPorts or Brew

### ISSUE THREAD

**Issue by jasperblues** [libimobiledevice/ifuse#5]

**Comment by mikeumus** [comment]
Homebrew says the `ifuse` formulae has been deprecated 😔

_ _ _ 

@nikias @FunkyM 
**Please turn on GitHub Sponsorship 🙏**

_ _ _ 

Searching `ifuse` on ports.MacPorts.org, shows:

```
Sorry, no matching ports found for "ifuse"
```

There is a `libimobiledevice` on Macports:
- https://ports.macports.org/port/libimobiledevice/summary

Will this macport be kept up to date in the near-future? 
Is `ifuse` in that macport?
