### ISSUE TITLE
Unknown AFC status 30 when mounting with --root

### ISSUE THREAD

**Issue by enricozb** [libimobiledevice/ifuse#80]
I have:
- iPhone 6s on iOS 14.7.1
- Apple File Conduit "2" v 1.1.5-1
- NixOS machine running the following compiled from source:
    - libplist: `106c4ee7f53ef800a82fce9638f29756e8b78640`
    - libimobiledevice-glue: `bc6c44b92091c9587a9bed0ed3f2c3248bfd13b3`
    - libusbmuxd: `a9a639d0102b9bbf30fd088e633c793316dbc873`
    - libimobiledevice: `ea6084c4ed624b6191b4b47737e33d88911bebc8` (with openssl)
    - ifuse: `6f5b8e410f9615b3369ca5eb5367745e13d83b92`
    - usbmuxd: `2839789bdb581ede7c331b9b4e07e0d5a89d7d18`

When I do `ifuse /mnt/ios/ --root -f` I get the following after trying to `ls /mnt/ios`:
```
Unknown AFC status 30.
Unknown AFC status 30.
```
printed a few times a second.

When `cd`-ing into `/mnt/ios` I get:
```
$ cd /mnt/ios
direnv: error LoadConfig() Getwd failed: stat .: input/output error
```

Is there something else I should be compiling from source?

`ifuse` works fine without `--root`.

Also, looking at [afc.h source](https://docs.libimobiledevice.org/libimobiledevice/latest/afc_8h.html) shows (I think) that status 30 is `AFC_E_MUX_ERROR`, but not sure what else to try here.

Any help would be appreciated.

**Comment by nikias** [comment]
Can you open another terminal and run `idevicesyslog` when you try to run ifuse? That might help to figure something out.

**Comment by enricozb** [comment]
Is there something I should filter the logs by? `idevicesyslog` prints a lot of info...

**Comment by enricozb** [comment]
When running `ifuse /mnt/ios --root -f` I get the following out of `idevicesyslog | rg lockdownd`:
```
$ idevicesyslog | rg lockdown
Apr  7 11:10:37 lockdownd[98] <Notice>: handle_get_value: <private>
Apr  7 11:10:37 lockdownd[98] <Notice>: handle_start_service: <private>
Apr  7 11:10:37 lockdownd[98] <Notice>: spawn_xpc_service: <private>
Apr  7 11:10:37 lockdownd[98] <Notice>: spawn_xpc_service_block_invoke: <private>
Apr  7 11:10:37 lockdownd[98] <Notice>: spawn_xpc_service_block_invoke: <private>
```
but when trying to `cd` or `ls` I don't see anything that useful. I'm weary of pasting the whole thing here, please let me know if there is a specific process you want me to report on

**Comment by enricozb** [comment]
An additional data point: if I downgrade afc2d to 1.1.2, then `ifuse /mnt/ios --root -f` takes much longer to output anything, but when `cd`-ing into `/mnt/ios` I get the same input/output error, but `ifuse` reports `Unknown AFC status 32.`, instead of `30`.

**Comment by enricozb** [comment]
Ok found something from `idevicesyslog`:
```
Apr  7 11:28:01 afc2d(libafc.dylib)[1759] <Notice>: RunServerThread: cannot setpriority: Operation not permitted
```

**Comment by enricozb** [comment]
@nikias Do you have any other debugging suggestions?

**Comment by enricozb** [comment]
It seems that I wasn't compiling from source correctly. I was still using the system `usbmuxd` when compiling `ifuse`. After making sure that I'm pulling from `HEAD` on all dependencies, it looks like it's working. Sorry for the fuss.
