### ISSUE TITLE
Consider adding fuse3 support

### ISSUE THREAD

**Issue by evelikov** [libimobiledevice/ifuse#90]
fuse2 is effectively EOL and its last release 2.9.9 was over 4 years ago.
Please consider switching to the actively maintained fuse3.

Thanks in advance

**Comment by tjex** [comment]
There is a pr #99 for this. But am worried it won't be merged. The repo is seemingly quiet from the maintainer side :grimacing:

**Comment by tjex** [comment]
awesome! This project is what enabled a complete switch to linux for me. Many thanks!!

**Comment by evelikov** [comment]
The PR has landed, closing this issue.

Thanks a bunch everyone. @nikias do you think we can have a new release with the fuse3 support?
